services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-node-app
    ports:
      - 3000:3000
    volumes:
      - container/database:/workspaces/
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
      MYSQL_DB: todos

  mysql:
    image: mysql:latest
    volumes:
      - /todo-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: todos

volumes:
  todo-mysql-data: